"""
integrations/openai_client.py
-----------------------------
Reusable OpenAI client for generating chat completions.
Follows production-grade patterns: environment-based config, singleton client, 
and robust error handling.
"""
from __future__ import annotations

import openai
from openai import AsyncOpenAI
from typing import Optional

from app.config.settings import get_settings
from app.utils.logger import get_logger

logger = get_logger(__name__)
settings = get_settings()

class OpenAIClient:
    """
    A production-grade OpenAI client integration.
    """
    
    _instance: Optional[AsyncOpenAI] = None

    def __init__(self):
        """
        Initializes the client using the API key from settings.
        Validates that the key exists to fail-fast.
        """
        self.api_key = settings.OPENAI_API_KEY.get_secret_value()
        if not self.api_key or "your-openai-key-here" in self.api_key:
            logger.error("Missing or placeholder OpenAI API Key in configuration.")
            raise ValueError("OPENAI_API_KEY is not configured correctly in .env")
        
        # Ensure we reuse the same client instance for connection pooling
        if OpenAIClient._instance is None:
            OpenAIClient._instance = AsyncOpenAI(api_key=self.api_key)
        self.client = OpenAIClient._instance

    async def generate_completion(self, prompt: str) -> str:
        """
        Calls the OpenAI Chat Completions API with gpt-4o-mini.
        
        Args:
            prompt: The user input text to send to the model.
            
        Returns:
            The text content generated by the AI.
            
        Raises:
            RuntimeError: If the API call fails or returns an invalid response.
        """
        logger.info("Sending prompt to OpenAI (gpt-4o-mini) | length: %d", len(prompt))
        
        # Mock override for testing the frontend without a real key
        if self.api_key == "sk-test-key-bypass-validation":
            logger.info("Using mock AI response for testing.")
            import asyncio
            await asyncio.sleep(2) # simulate network latency
            return '{"industry": "EdTech", "target_users": "University Students", "problem": "Lack of personalized tutoring", "solution_type": "AI Adaptive Learning", "revenue_model": "Freemium Subscription"}'

        try:
            response = await self.client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a helpful and professional AI startup consultant."},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
                max_tokens=1000
            )
            
            content = response.choices[0].message.content
            if not content:
                logger.error("OpenAI returned an empty response body.")
                raise RuntimeError("Received empty response from OpenAI.")
            
            logger.info("Successfully received response from OpenAI.")
            return content

        except openai.AuthenticationError as e:
            logger.critical("OpenAI Authentication failed. Check your API key.")
            raise RuntimeError(f"OpenAI Authentication Error: {str(e)}") from e
            
        except openai.RateLimitError as e:
            logger.warning("OpenAI Rate limit reached.")
            raise RuntimeError(f"OpenAI Rate Limit Exceeded: {str(e)}") from e
            
        except openai.APIConnectionError as e:
            logger.error("OpenAI Network connection failed.")
            raise RuntimeError(f"OpenAI Network Error: {str(e)}") from e
            
        except Exception as e:
            logger.error("OpenAI Integration Error: %s", str(e))
            raise RuntimeError(f"OpenAI API Failure: {str(e)}") from e
