"""
services/report_export_service.py
-------------------------------
Service for exporting generated startup reports into various formats (starting with Markdown).
"""
from __future__ import annotations

from app.services.report_generation_service import ReportGenerationResult
from app.utils.logger import get_logger

logger = get_logger(__name__)


class ReportExportService:
    """
    Handles formatting and exporting of synthesized startup reports.
    """

    @staticmethod
    def to_markdown(report: ReportGenerationResult, startup_name: str = "Startup Idea Analysis") -> str:
        """
        Converts a ReportGenerationResult object into a clean, structured Markdown string.
        """
        logger.info("Converting report to Markdown format...")

        markdown_content = f"""# {startup_name} Report

# Executive Summary
{report.executive_summary}

# Problem and Solution
{report.problem_solution_analysis}

# Market Opportunity
{report.market_opportunity}

# Competitor Landscape
{report.competitor_landscape}

# Startup Feasibility
{report.startup_score_summary}

---
*Generated by AI Startup Analyst suite.*
"""
        logger.debug("Markdown conversion complete.")
        return markdown_content

    @staticmethod
    def to_pdf(markdown_content: str) -> bytes:
        """
        Converts markdown content into a professional PDF document.
        Uses markdown to convert to HTML, then WeasyPrint for PDF generation.
        """
        import markdown
        from weasyprint import HTML
        
        logger.info("Converting report to PDF format...")

        # 1. Convert Markdown to HTML
        html_body = markdown.markdown(markdown_content, extensions=['extra', 'codehilite'])
        
        # 2. Add some premium CSS for the PDF
        premium_css = """
        @page {
            margin: 2cm;
            @bottom-right {
                content: "Page " counter(page);
                font-size: 9pt;
                color: #666;
            }
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            font-size: 11pt;
        }
        h1 {
            color: #1a365d;
            border-bottom: 2px solid #1a365d;
            padding-bottom: 10px;
            margin-top: 30px;
        }
        h2 {
            color: #2c5282;
            margin-top: 25px;
        }
        p {
            margin-bottom: 15px;
            text-align: justify;
        }
        hr {
            border: none;
            border-top: 1px solid #e2e8f0;
            margin: 40px 0;
        }
        """

        full_html = f"""
        <html>
            <head>
                <style>{premium_css}</style>
            </head>
            <body>
                {html_body}
            </body>
        </html>
        """

        # 3. Generate PDF
        pdf_bytes = HTML(string=full_html).write_pdf()
        
        logger.debug("PDF generation complete (%d bytes).", len(pdf_bytes))
        return pdf_bytes
